name: jeanswest
description: Flutter (Android) JeansWest App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#----------------Global-----------------

  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  easy_localization: ^3.0.0
#!  toast: ^0.1.5 (backup pack)
  flutter_easyloading: ^3.0.0 
#!  bot_toast: ^3.0.5 (backup pack)
#!  flash: ^1.5.0 (backup pack)
#!
  #! integration_test: ^1.0.1
  #? flutter_keyboard_visibility: ^4.0.0
  flutter_keyboard_visibility: any
  # ?
  flutter_phoenix: ^1.0.0
  flutter_dotenv: ^5.0.0
  flutter_config: ^2.0.0
#----------------Connectivity and DataBase-----------------
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  get_it: ^6.0.0
  pretty_dio_logger: ^1.1.1
  logging: any
  shared_preferences: ^2.0.4
  connectivity: ^3.0.2
  intent: ^1.4.0
#!  social_share: ^2.0.5 (backup pack)
  sqflite: ^2.0.0+2
  synchronized: ^3.0.0
  #
  firebase_dynamic_links: any
  firebase_messaging: any
  cloud_firestore: any
  # 
  http: any
  permission_handler: ^8.1.2
#----------------UI Widgets-----------------
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  percent_indicator: ^2.1.9+1
  sliding_up_panel: ^1.0.2
  flutter_svg: any
  flutter_html: ^1.3.0
  dotted_border: ^2.0.0
  fdottedline: ^1.0.1
  carousel_slider: ^3.0.0
  configurable_expansion_tile: any
  extended_text: ^7.0.0
  flutter_dialogs: ^1.1.0
  #! rflutter_alert: ^2.0.2 (backup pack)
  pinput: ^1.2.0
  drop_cap_text: ^1.1.3
  screenshot: ^0.3.0
  flutter_switch: ^0.3.1
# 
  flutter_gifimage: ^1.0.0
  # qr_code_scanner: ^0.5.1
  # flutter_barcode_scanner: ^2.0.0
  # flutter_barcode_scanner: any
  qrscan: ^0.3.2
#----------------Converts-----------------
  qr_flutter: ^4.0.0
  shamsi_date: ^0.9.1


#----------------Map-----------------

  # google_maps_flutter: any
  # google_maps_flutter: ^2.0.6
  google_maps_flutter: ^0.5.26
#! google_maps_flutter: ^2.0.1 (backup pack)
  #! flutter_map: ^0.10.1+1 (backup pack)
  latlong: any
  # 
  geolocator: any
  # geocoding: any
  # geocoding: ^1.0.0
  geocoding: ^2.0.0
  location: any

  # search_map_place: ^0.3.0
  search_map_place: any
  
#-------------------------------------------------------------------

# dependency_overrides:
  # flutter_html: ^2.0.0-nullsafety.1
  # retrofit_generator: ^2.0.0+1
  # firebase_dynamic_links: ^0.5.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  build_runner: any



# analyzer:
#   language:
#     enableSuperMixins: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #---------------Environment-----------------
    - .env
    #---------------Translations----------------
    - assets/translations/
    #------------------Image--------------------
    - assets/images/
    #------------------PNG Image--------------------
    - assets/images/png_images/
    - assets/images/png_images/global/
    - assets/images/png_images/global/logo/
    - assets/images/png_images/global/userProfile/
    - assets/images/png_images/branch/
    - assets/images/png_images/product/
    - assets/images/png_images/profile/
    - assets/images/png_images/profile/more/
    - assets/images/png_images/profile/levelCards/
    #------------------SVG Image--------------------
    - assets/images/svg_images/
    - assets/images/svg_images/branch/
    - assets/images/svg_images/global/
    - assets/images/svg_images/global/bottom_navigation_bar/
    - assets/images/svg_images/global/message/
    - assets/images/svg_images/global/new/
    - assets/images/svg_images/login/
    - assets/images/svg_images/login/flags/
    - assets/images/svg_images/profile/
    - assets/images/svg_images/profile/coupons_info/
    - assets/images/svg_images/profile/invite_friends/
    - assets/images/svg_images/profile/more/
    - assets/images/svg_images/store/category/
    - assets/images/svg_images/store/category/color/
      #------------------GIF Image--------------------
    - assets/images/gif_images/
    - assets/images/gif_images/global/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/iransans_web_fa_num/IRANSansWeb(FaNum).ttf
    - family: IRANSansLight
      fonts:
        - asset: assets/fonts/iransans_web_fa_num/IRANSansWeb(FaNum)_Light.ttf
    - family: IRANSansBold
      fonts:
        - asset: assets/fonts/iransans_web_fa_num/IRANSansWeb(FaNum)_Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
